name: Cypress example tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cypress example tests
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Cypress run
        uses: cypress-io/github-action@v5
